var host="http://vaf.vegasmb.com:8101/VAFService/Service.svc",prevId,curWindowId,dtpickertheme="default",swatchSelected="a",deviceAgent=navigator.userAgent.toLowerCase(),isMobile=-1<deviceAgent.indexOf("mobile"),initTheme="themes/default.css",matches=null,classes="ui-body-a ui-body-b ui-body-c ui-body-d ui-body-e ui-body-f ui-body-g",classesBar="ui-bar-a ui-bar-b ui-bar-c ui-bar-d ui-bar-e ui-bar-f ui-bar-g";
$(document).delegate('[data-role="page"]',"pagecreate",function(){if("myApps"==prevId){var a=new XMLHttpRequest;a.open("GET",$("link[href*='themes']").prop("href"),!0);a.onreadystatechange=function(){if(4===a.readyState&&(0===a.status||200===a.status||304===a.status))matches=a.responseText.match(/\/\*\s[A-Z]\s*-*\*\//g),loadThemes()};a.send(null)}});
function loadThemes(){for(var a=classes="",b=0;b<matches.length;b++){var c=String.fromCharCode(65+b),d=String.fromCharCode(97+b);classes+="ui-body-"+d+" ";classesBar+="ui-body-"+d+" ";a+='<li data-theme="'+d+'"><a onclick="changeSwatch(&quot;'+d+"&quot;, &quot;Theme "+c+'&quot;);">Theme '+c+"</a></li>"}$("#lstThemes").html(a);try{$("#lstThemes").listview("refresh")}catch(e){}}
$(document).delegate('[data-role="page"]',"pagecreate",function(){$(this).removeClass(classes).addClass("ui-body-"+swatchSelected).attr("data-theme",swatchSelected);null!=$(this).children(".ui-header")&&$(this).children(".ui-header").removeClass(classes).addClass("ui-bar-"+swatchSelected).attr("data-theme",swatchSelected);null!=$(this).children(".ui-footer")&&$(this).children(".ui-footer").removeClass(classes).addClass("ui-bar-"+swatchSelected).attr("data-theme",swatchSelected)});
$(document).delegate('[data-role="page"]',"pagebeforehide",function(){setTimeout(function(){$.mobile.showPageLoadingMsg()},1)});$(document).delegate('[data-role="page"], [data-role="dialog"]',"pageshow",function(){setTimeout(function(){$.mobile.hidePageLoadingMsg()},100)});
$(document).delegate(".newPage, #mapPage, #routePage","refresh",function(a,b){var c=$(this).attr("data-theme")||"a",b=b||"a";c!=b&&($(curWindowId+" .ui-body-"+c).each(function(){$(this).removeClass("ui-body-"+c).addClass("ui-body-"+b)}),$(curWindowId+" .ui-btn-up-"+c).each(function(){$(this).removeClass("ui-btn-up-"+c).addClass("ui-btn-up-"+b)}),$(curWindowId+" .ui-btn-down-"+c).each(function(){$(this).removeClass("ui-btn-down-"+c).addClass("ui-btn-down-"+b)}),$(this).find("*[data-theme]").each(function(){$(this).attr("data-theme",
b)}),null!=$(this).children(".ui-header")&&$(this).children(".ui-header").attr("data-theme",b).removeClass(classesBar).addClass("ui-bar-"+b),null!=$(this).children(".ui-footer")&&$(this).children(".ui-footer").attr("data-theme",b).removeClass(classesBar).addClass("ui-bar-"+b),$(this).attr("data-theme",b).removeClass("ui-body-"+c).addClass("ui-body-"+b).trigger("create"))});
function changePage(a){curWindowId=a;prevId=$.mobile.activePage.prop("id");$.mobile.changePage(jQuery(a));"#myApps"!=a&&$(a).trigger("refresh",swatchSelected)}function changeSwatch(a,b){swatchSelected=a;changePage(curWindowId);loadThemes();$("#selectTheme .ui-btn-text").text(b)}$("#mainPage").live("pageshow",function(){changePage("#myApps")});
$("#myApps").live("pageshow",function(){swatchSelected="a";$("link[href*='themes']").prop("href",initTheme);$.mobile.showPageLoadingMsg();$.ajax({url:host+"/GetCurrentApps?method=?",data:{},type:"GET",dataType:"jsonp",success:function(a){$.mobile.hidePageLoadingMsg();var a=jQuery.parseJSON(a),b="";$.each(a.myApps,function(a,d){b+='<li><a id="'+d.Id+"#"+d.CustomTheme+'" onclick="openApp(this);">'+d.Name+"</a></li>"});$("#listMyApps").html(b);$("#listMyApps").listview("refresh")},error:function(){showMessage("Error while trying to load data from the server !");
$.mobile.hidePageLoadingMsg()}});$(this).removeClass(classes).addClass("ui-body-"+swatchSelected).attr("data-theme",swatchSelected)});var selectedApp="";
function openApp(a){a=a.id.split("#");if(0!=a.length){$.mobile.showPageLoadingMsg();""!=jQuery.trim(a[1])&&"null"!=a[1]&&$("link[href*='themes']").prop("href",a[1]);var b=host+"/GetCurrentApp?method=?";selectedApp=a[0];$.ajax({url:b,data:{appID:selectedApp,theme:swatchSelected},type:"GET",dataType:"jsonp",success:function(a){$.mobile.hidePageLoadingMsg();a=jQuery.parseJSON(a.GetCurrentAppResult);$("div").remove(".newPage");$("#page_body").append(a.html);$.mobile.initializePage();changePage("#"+a.pageid);
for(var b=0;b<a.pages.length;b++)$.mobile.loadPage("#"+a.pages[b]);$.mobile.loadPage("#mapPage");$.mobile.loadPage("#routePage");for(b=0;b<a.dateIds.length;b++)makeDatePicker(a.dateIds[b]);for(b=0;b<a.timeIds.length;b++)makeTimePicker(a.timeIds[b]);for(b=0;b<a.dateTimeIds.length;b++)makeDateTimePicker(a.dateTimeIds[b])},error:function(){showMessage("Error while trying to load data from the server !");$.mobile.hidePageLoadingMsg()}})}}
function makeDatePicker(a){$("#"+a).scroller({theme:dtpickertheme,dateFormat:"dd.mm.yy",dateOrder:"ddmmy"});$("#"+a).scroller("setDate",new Date,!0)}function makeTimePicker(a){$("#"+a).scroller({preset:"time",theme:dtpickertheme,ampm:!1,stepMinute:5,timeFormat:"HH:ii"});$("#"+a).scroller("setDate",new Date,!0)}
function makeDateTimePicker(a){$("#"+a).scroller({preset:"datetime",theme:dtpickertheme,dateFormat:"dd.mm.yy",ampm:!1,stepMinute:5,timeFormat:"HH:ii",dateOrder:"ddmmy"});$("#"+a).scroller("setDate",new Date,!0)}
function showMessage(a){$("<div id='notification' class='ui-loader ui-overlay-shadow ui-body-e ui-corner-all' style='padding:5px 15px;'><h1>"+a+"</h1></div>").css({display:"block",opacity:0.96,top:$(window).scrollTop()+100}).appendTo($.mobile.pageContainer).delay(800).fadeOut(800,function(){$(this).remove()})}var address="";
function showMap(a){address=$(a).val();if(""!=address){$("#backMap").attr("onclick",'changePage("#'+$.mobile.activePage.prop("id")+'")');try{$("#map-canvas").gmap("destroy")}catch(b){}changePage("#mapPage");(new google.maps.Geocoder).geocode({address:address},function(a,b){if(b==google.maps.GeocoderStatus.OK)lat=a[0].geometry.location.lat(),lng=a[0].geometry.location.lng();else return showMessage("Cannot locate the address !"),!1;var e=new google.maps.LatLng(lat,lng);$("#map-canvas").gmap({center:e,
zoom:14}).bind("init",function(a,b){$("#map-canvas").gmap("addMarker",{position:b.getCenter(),animation:google.maps.Animation.DROP})})})}else showMessage("Address is empty !")}function showRoute(a){address="";address=$(a).val();""!=address?($("#backRoute").attr("onclick",'changePage("#'+$.mobile.activePage.prop("id")+'")'),changePage("#routePage")):showMessage("Address is empty !")}
$("#routePage").live("pageshow",function(){$.mobile.showPageLoadingMsg();if(""!=address){try{$("#route_canvas").gmap("destroy")}catch(a){}$("#route_canvas").gmap().bind("init",function(){$("#route_canvas").gmap("getCurrentPosition",function(a,c){if("OK"===c){var d=new google.maps.LatLng(a.coords.latitude,a.coords.longitude);$("#route_canvas").gmap("displayDirections",{origin:d,destination:address,travelMode:google.maps.DirectionsTravelMode.DRIVING},{panel:document.getElementById("results")},function(a){$.mobile.hidePageLoadingMsg();
a?showMessage("Get directions successfully !"):showMessage("Get directions failed !")})}else $.mobile.hidePageLoadingMsg(),showMessage("Cannot get the location !")})})}OnResizePage()});function doCall(a,b){var c=$(a).val();""!=c?$(b).prop("href","tel:"+c):showMessage("Please enter the phone number !")}function sendSMS(a,b){var c=$(a).val();""!=c?$(b).prop("href","sms:"+c):showMessage("Please enter the phone number !")}
function sendMail(a,b){var c=$(a).val();""!=c?$(b).prop("href","mailto:"+c):showMessage("Please enter the email address !")}function onSendMail(a){$.mobile.hidePageLoadingMsg();""==a.result?showMessage("Email sent successfully !"):showMessage("Failed to send mail with error: "+a.result)}
$(document).delegate(".newPage","pageshow",function(){if(null!=$('[data-role="navbar"]')){var a=$.trim($(this).prop("id"));$("#ul"+a+" a").removeClass("ui-btn-active ui-state-persist");$("#ul"+a+" a").each(function(){-1!=$.trim($(this).prop("class")).indexOf(a)&&$(this).addClass("ui-btn-active ui-state-persist")})}arrangeWindows($(this))});
function arrangeWindows(a){var b=window.innerHeight,c=window.innerWidth,d=0,e=$(a).children(".ui-content").height(),a=$.trim($(a).prop("id")),f=$("#"+a+" .ui-collapsible").length,g=e/f;1<f?$("#"+a+" .ui-collapsible").each(function(){$(this).removeClass("content-left content-right");if(c>b){var a=parseFloat($(this).css("padding-top")),h=parseFloat($(this).css("padding-bottom")),i=$("#"+$(this).attr("id")+" h3").height();$(this).addClass(0==d%2?"content-left":"content-right");$(".window").css("height",
e-a-h-i-55);d++}else $(".window").css("height",g-70)}):$("#"+a+" .ui-collapsible").each(function(){$(this).removeClass("content-left content-right");var a=parseFloat($(this).css("padding-top")),b=parseFloat($(this).css("padding-bottom")),c=$("#"+$(this).attr("id")+" h3").height();$(".window").css("height",e-a-b-c-55)})}function OnResizePage(){if("routePage"==$.mobile.activePage.prop("id")){var a=$.mobile.activePage.children(".ui-content");$("#route_canvas").css("height",a.height())}}
$(window).bind("orientationchange",function(){OnResizePage();arrangeWindows($.mobile.activePage)});
function onIncludeSelectedModule(a){$.mobile.hidePageLoadingMsg();var b=$("#"+a.pageid).children(":jqmData(role=content)");b.html(a.html);$("#"+a.pageid).page();b.find(":jqmData(role=listview)").listview();$.mobile.changePage($("#"+a.pageid));for(b=0;b<a.dateIds.length;b++)makeDatePicker(a.dateIds[b]);for(b=0;b<a.timeIds.length;b++)makeTimePicker(a.timeIds[b]);for(b=0;b<a.dateTimeIds.length;b++)makeDateTimePicker(a.dateTimeIds[b])}var wrapperId,pageIndexes=[],scrollers=[];
function pullUpAction(a,b){wrapperId=a;$.ajax({url:host+"/GetPageData?method=?",data:{windowWrapperId:a,pageIndex:b},type:"GET",dataType:"jsonp",success:onGetPageData,error:function(){showMessage("Error while trying to load data from the server !");$.mobile.hidePageLoadingMsg()}})}
function pullDownAction(a,b){wrapperId=a;$.ajax({url:host+"/GetPageData?method=?",data:{windowWrapperId:a,pageIndex:b},type:"GET",dataType:"jsonp",success:onGetPageData,error:function(){showMessage("Error while trying to load data from the server !");$.mobile.hidePageLoadingMsg()}})}
function onGetPageData(a){a=jQuery.parseJSON(a.GetPageDataResult);$("#"+wrapperId+" .iscroller").empty();$("#"+wrapperId+" .iscroller").html(a.html);$.mobile.activePage.trigger("create");for(var b=0;b<a.dateIds.length;b++)makeDatePicker(a.dateIds[b]);for(b=0;b<a.timeIds.length;b++)makeTimePicker(a.timeIds[b]);for(b=0;b<a.dateTimeIds.length;b++)makeDateTimePicker(a.dateTimeIds[b]);$("#"+wrapperId).scrollview("scrollTo",0,0)};